apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-apps
  labels:
    name: sosmed-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sosmed-apps
  template:
    metadata:
      name: sosmed-apps
      labels:
        name: sosmed-apps
    spec:
      containers:
        - name: sosmed-apps
          image: DOCKER_NAME
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sosmed-apps-service
spec:
  type: NodePort
  selector:
    name: sosmed-apps
  ports:
    - port: 80
      targetPort: 80
